// src/components/ChessSquare.vue
<template>
  <div
    :class="[
      'chess-square',
      squareColor,
      {
        'highlighted': isHighlighted,
        'selected': isSelected
      }
    ]"
    @click="$emit('click')"
  >
    <span v-if="piece" class="chess-piece">
      {{ getPieceSymbol(piece.type, piece.color) }}
    </span>
    <div 
      v-if="isHighlighted && !piece" 
      class="w-4 h-4 bg-emerald-400 rounded-full opacity-70 animate-pulse"
    />
  </div>
</template>

<script setup lang="ts">
import { ChessPiece, Position } from '../types/chess';
import { getPieceSymbol } from '../utils/pieceSymbols';

interface Props {
  position: Position;
  piece: ChessPiece | null;
  squareColor: 'light' | 'dark';
  isHighlighted: boolean;
  isSelected: boolean;
}

defineProps<Props>();
defineEmits<{
  click: [];
}>();
</script>

// src/components/ChessSquare.tsx
import React from 'react';
import clsx from 'clsx';
import { ChessPiece, Position } from '../types/chess';
import { getPieceSymbol } from '../utils/pieceSymbols';

interface ChessSquareProps {
  position: Position;
  piece: ChessPiece | null;
  squareColor: 'light' | 'dark';
  isHighlighted: boolean;
  isSelected: boolean;
  onClick: () => void;
}

const ChessSquare: React.FC<ChessSquareProps> = ({
  position,
  piece,
  squareColor,
  isHighlighted,
  isSelected,
  onClick
}) => {
  return (
    <div
      className={clsx(
        'chess-square',
        squareColor,
        {
          'highlighted': isHighlighted,
          'selected': isSelected
        }
      )}
      onClick={onClick}
    >
      {piece && (
        <span className="chess-piece">
          {getPieceSymbol(piece.type, piece.color)}
        </span>
      )}
      {isHighlighted && !piece && (
        <div className="w-4 h-4 bg-emerald-400 rounded-full opacity-70 animate-pulse" />
      )}
    </div>
  );
};

export default ChessSquare;
